### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by barungh** [MarcHanin/drun#3]
```
Download https://deno.land/x/drun@v1.1.0/src/errors/drun_config_validation_error.ts
error: TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    await Deno.symlink(originSrcFilePath, dest, {
                                                
    at https://deno.land/std@v0.52.0/fs/copy.ts:117:49

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    Deno.symlinkSync(originSrcFilePath, dest, {
                                              
    at https://deno.land/std@v0.52.0/fs/copy.ts:141:47

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    await Deno.symlink(src, dest, {
                                  
    at https://deno.land/std@v0.52.0/fs/ensure_symlink.ts:33:35

TS2345 [ERROR]: Argument of type '{ type: string; }' is not assignable to parameter of type 'string'.
    Deno.symlinkSync(src, dest, {
                                
    at https://deno.land/std@v0.52.0/fs/ensure_symlink.ts:65:33

Found 4 errors.
```

**Comment by MarcHanin** [comment]
Thanks for reporting this error.
Can I have more informations about your environment, like OS and Deno version ?
If you use Deno 1.0.0 you have two solutions:
1) Install Drun v1.0.0 (deno install --allow-read --allow-run --unstable https://deno.land/x/drun@v1.0.0/drun.ts) and execute it with `drun [OPTIONS]`  instead of `drun watch [OPTIONS]`.
more informations on Drun v1.0.0 documentation: https://github.com/MarcHanin/drun/tree/v1.0.0
2) Upgrade your Deno version to Deno v1.0.1 with `deno upgrade`

**Comment by barungh** [comment]
Hi there,
Thank You 

It worked with the commands you mentioned
```deno install --allow-read --allow-run --unstable https://deno.land/x/drun@v1.0.0/drun.ts``` 
instead of 
```deno install --allow-read --allow-run --unstable https://deno.land/x/drun@v1.1.0/drun.ts```
my deno version is 1.0.0

Thank You

**Comment by MarcHanin** [comment]
Yes it was because of the Deno version `v1.0.0` not compatible with Drun `v1.1.0`, glad to know it works now :smile:
